// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecRawQuery(arg1) {
  return window['go']['main']['App']['ExecRawQuery'](arg1);
}

export function GetScripts() {
  return window['go']['main']['App']['GetScripts']();
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}

export function GetTriggers() {
  return window['go']['main']['App']['GetTriggers']();
}

export function GetViews() {
  return window['go']['main']['App']['GetViews']();
}

export function NewDatabase(arg1) {
  return window['go']['main']['App']['NewDatabase'](arg1);
}

export function OpenDatabase() {
  return window['go']['main']['App']['OpenDatabase']();
}

export function OpenInMemoryDatabase() {
  return window['go']['main']['App']['OpenInMemoryDatabase']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SelectTable(arg1) {
  return window['go']['main']['App']['SelectTable'](arg1);
}
