// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecRawQuery(arg1:string):Promise<Array<{[key: string]: any}>>;

export function GetTables():Promise<Array<{[key: string]: any}>>;

export function GetViews():Promise<Array<{[key: string]: any}>>;

export function SelectTable(arg1:string):Promise<Array<{[key: string]: any}>>;
