// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecRawQuery(arg1) {
  return window['go']['main']['App']['ExecRawQuery'](arg1);
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}

export function GetViews() {
  return window['go']['main']['App']['GetViews']();
}

export function NewDatabase(arg1) {
  return window['go']['main']['App']['NewDatabase'](arg1);
}

export function OpenDatabase() {
  return window['go']['main']['App']['OpenDatabase']();
}

export function OpenInMemoryDatabase() {
  return window['go']['main']['App']['OpenInMemoryDatabase']();
}

export function SelectTable(arg1) {
  return window['go']['main']['App']['SelectTable'](arg1);
}
